[versions]
kotlin = "2.4.0"
shadow = "9.6.0"

kotlinx-serialization = "1.11.0"
kotlinx-coroutines = "1.10.2"
velocity = "4.1.0-SNAPSHOT"
mccoroutine = "2.22.0"
lettuce = "7.6.0.RELEASE"
graph = "0.1.0-R0.2-SNAPSHOT"
nanoid = "2.0.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
mccoroutine-velocity-api = { module = "com.github.shynixn.mccoroutine:mccoroutine-velocity-api", version.ref = "mccoroutine" }
mccoroutine-velocity-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-velocity-core", version.ref = "mccoroutine" }
lettuce-core = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
graph = { module = "net.azisaba.graph:graph", version.ref = "graph" }
nanoid = { module = "io.viascom.nanoid:nanoid", version.ref = "nanoid" }
